# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\35382\Desktop\code\pyqt5的学习\UI\my_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MyMainWindow(object):
    def setupUi(self, MyMainWindow):
        MyMainWindow.setObjectName("MyMainWindow")
        MyMainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/github.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MyMainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MyMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(230, 180, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(330, 180, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(400, 180, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        MyMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MyMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MyMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MyMainWindow)
        self.statusbar.setObjectName("statusbar")
        MyMainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MyMainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad = QtWidgets.QAction(MyMainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionExit = QtWidgets.QAction(MyMainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionVersion = QtWidgets.QAction(MyMainWindow)
        self.actionVersion.setObjectName("actionVersion")
        self.actionUpdata = QtWidgets.QAction(MyMainWindow)
        self.actionUpdata.setObjectName("actionUpdata")
        self.actionRefresh = QtWidgets.QAction(MyMainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/refresh"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefresh.setIcon(icon1)
        self.actionRefresh.setObjectName("actionRefresh")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionRefresh)
        self.menuAbout.addAction(self.actionVersion)
        self.menuAbout.addAction(self.actionUpdata)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MyMainWindow)
        self.pushButton.clicked.connect(self.spinBox.stepUp) # type: ignore
        self.pushButton_2.clicked.connect(self.spinBox.stepDown) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MyMainWindow)

    def retranslateUi(self, MyMainWindow):
        _translate = QtCore.QCoreApplication.translate
        MyMainWindow.setWindowTitle(_translate("MyMainWindow", "主窗体测试"))
        self.pushButton.setText(_translate("MyMainWindow", "+"))
        self.pushButton_2.setText(_translate("MyMainWindow", "-"))
        self.menuFile.setTitle(_translate("MyMainWindow", "File"))
        self.menuEdit.setTitle(_translate("MyMainWindow", "Edit"))
        self.menuAbout.setTitle(_translate("MyMainWindow", "About"))
        self.actionSave.setText(_translate("MyMainWindow", "Save"))
        self.actionLoad.setText(_translate("MyMainWindow", "Load"))
        self.actionExit.setText(_translate("MyMainWindow", "Exit"))
        self.actionVersion.setText(_translate("MyMainWindow", "Version"))
        self.actionUpdata.setText(_translate("MyMainWindow", "Updata"))
        self.actionRefresh.setText(_translate("MyMainWindow", "刷新"))
from UI import resource_rc
